### ISSUE TITLE
prometheus-operator high CPU usage

### ISSUE THREAD

**Issue by Paxa** [coreos/prometheus-operator#1659]
After changing some ServiceMonitor and Service it started to syncing often (4-6 times per second) and consume lots of CPU 

Server `top`:
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                       
 4055 root      20   0 1289564 780892  24920 S  44.1 10.0 657:10.56 /hyperkube apiserver --advertise-address=159.69.46.22 --etcd-servers=https://159.69.46.22:2379 --etcd-cafile=/etc/ssl/etcd/ss+
11007 root      20   0   57964  30048   5560 S  41.2  0.4 111:27.01 /bin/operator --kubelet-service=kube-system/kubelet --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0+
 2934 root      20   0   10.8g 570904  28152 S  29.4  7.3 254:45.36 /usr/local/bin/etcd                                                                                                           
```

operator logs:
```
level=info ts=2018-07-22T13:42:19.488531966Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:19.673520342Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:19.926435905Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:20.217087316Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:20.377151554Z caller=operator.go:400 component=alertmanageroperator msg="sync alertmanager" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:20.532518265Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:20.703567261Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:20.907221323Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:21.580574057Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:21.76928422Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:21.984846144Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:22.162221857Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:22.352269176Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:22.493064909Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:22.7352912Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:22.983950194Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:23.175734439Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:23.335383162Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:23.468575212Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:23.656169945Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:23.988038254Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:24.142248531Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:24.35380114Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:24.538068047Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:24.784743416Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:25.039094124Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:25.181452826Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:25.320558779Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:25.452268213Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:25.653005215Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:25.864405214Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:26.130965577Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:26.372177244Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:26.527136827Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:26.698098587Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:26.915618298Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:27.170208284Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:27.356296116Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
level=info ts=2018-07-22T13:42:27.583503043Z caller=operator.go:737 component=prometheusoperator msg="sync prometheus" key=monitoring/kube-prometheus
```

**Comment by mxinden** [comment]
@Paxa Thanks for reporting the issue. Which Prometheus Operator version is this?

**Comment by Capitrium** [comment]
@mxinden We're seeing the same issue here on 0.22.x - we noticed this after upgrading from 0.19.0.

<img width="1894" alt="prometheus-operator-cpu-usage" src="https://user-images.githubusercontent.com/5111534/43400396-fb063e22-93e3-11e8-9b12-ba566e5bd325.png">

**Comment by mxinden** [comment]
@Paxa @Capitrium I just merged https://github.com/coreos/prometheus-operator/pull/1718, which should fix parts of your issue, if not all. So far I was not able to fully reproduce it.

Would you mind testing out the current `quay.io/coreos/prometheus-operator:master` in your test environment?

**Comment by Capitrium** [comment]
@mxinden Current master has the same behaviour. Looking at the new metrics that were added in that PR, it seems like it's updates to the StatefulSets that are triggering the excessive syncing:

<img width="1274" alt="screen shot 2018-08-01 at 10 51 00 am" src="https://user-images.githubusercontent.com/5111534/43525672-d814af84-9578-11e8-9a3a-353ba86f08c3.png">

Running a diff on the StatefulSets that the operator generates, I can see that there are a few differences in the current master version that might cause issues (Prometheus pods were crash-looping after the upgrade):

1) The `--web.console.libraries` argument on the prometheus container changed, not sure if that's intentional:
```
- --web.console.libraries=/etc/prometheus/console-libraries -> - --web.console.libraries=/etc/prometheus/console_libraries
```

2) A `--log-format=logfmt` argument was added to the `prometheus-config-reloader`; the value `logfmt` seems incorrect.

Most importantly, I can see that the `prometheus-operator-input-checksum` annotation value has changed between the two StatefulSets even though the source rules have not changed. This also occurs on `v0.22.2`; it seems to me that the input checksum calculation is not deterministic, causing the annotation to be updated on StatefulSets multiple times per second, in turn causing the excessive syncing and high cpu usage.

**Comment by mxinden** [comment]
@Capitrium Thanks a lot for the detailed debugging! Very helpful.

In regards to the location change of the `console-libraries`. This was a bug on the Prometheus Operator fixed in https://github.com/coreos/prometheus-operator/pull/1653.

> A --log-format=logfmt argument was added to the prometheus-config-reloader; the value logfmt seems incorrect.

Can you elaborate further on this? Is the prometheus-config-reloader logging any errors?

---

In regards to the StatefulSet input checksum changing: Great catch. We are still not able to reproduce this, but I prepared a patch that might solve the issue (https://github.com/coreos/prometheus-operator/pull/1737). It is already merged. Could you try the current `:master` tag once again?

**Comment by Capitrium** [comment]
> Can you elaborate further on this? Is the prometheus-config-reloader logging any errors?

I was unfamiliar with the `logfmt` logging format (I was expecting something like `json`, `systemd`, `combined`, etc.) so this isn't actually an issue.

---

Unfortunately, the current `master` image doesn't seem to have fixed the checksum issue:
```
$ for ((i=1;i<=3;i++)); do d=`date`; r=`kubectl get statefulset -n monitoring prometheus-k8s -o yaml | grep prometheus-operator-input-hash`; echo "$d: $r"; sleep 1; done
Thu  2 Aug 2018 18:00:11 ADT:     prometheus-operator-input-hash: "3205407446252155568"
Thu  2 Aug 2018 18:00:13 ADT:     prometheus-operator-input-hash: "6097306340522292192"
Thu  2 Aug 2018 18:00:14 ADT:     prometheus-operator-input-hash: "15372938863727082316"
```

**Comment by mxinden** [comment]
@capitrium thanks for testing this out so quickly.

Could you give me some more details on your cluster setup like:

- Kubernetes Version
- Which Prometheus Operator features you are using (alerting, custom
Kubernetes sd, ...)
- If you are selecting Rules and ServiceMonitors across namespaces
- ...

Are you able to reproduce this on minikube with the kube-prometheus stack?

**Comment by Capitrium** [comment]
@mxinden No problem! Our current configuration is based on the kube-prometheus stack (although from several versions ago):

- Kubernetes 1.9.3_coreos_0
- Standard kube-prometheus metrics / alerts
- No custom service discovery / prometheus configs, etc.
- Added ServiceMonitors and alerting rules for additional services
- Updated alerting config with Slack integration
- No cross-namespace resource selection; all rules / ServiceMonitors in the same namespace as prometheus-operator

Currently, the single `prometheus-k8s` cluster is used for the majority of our metrics and alerting rules. I've spun up a second cluster with a much smaller set of alerting rules, and it does not show this issue:
```
$ for ((i=1;i<=3;i++)); do d=`date`; r=`kubectl get statefulset -n monitoring prometheus-test -o yaml | grep prometheus-operator-input-hash`; echo "$d: $r"; sleep 1; done
Thu  2 Aug 2018 20:51:42 ADT:     prometheus-operator-input-hash: "13833528202023545621"
Thu  2 Aug 2018 20:51:44 ADT:     prometheus-operator-input-hash: "13833528202023545621"
Thu  2 Aug 2018 20:51:45 ADT:     prometheus-operator-input-hash: "13833528202023545621"
```

The only differences that I can see between the `k8s` and `test` clusters are that we have more rules configured and are mounting extra Secrets on the `k8s` cluster; the `test` cluster is very barebones. I'll do some testing tomorrow to see if I can reproduce this issue on minikube.

**Comment by Capitrium** [comment]
@mxinden I haven't been able to reproduce this in minikube yet, however I'm starting to suspect the `PrometheusStatus` subresource as the cuprit.

Looking at the code (and let me know if I'm wrong here), the input hash is calculated from the entire `Prometheus` resource, the operator's `Config`, and the prometheus rule file names. The list of rule file names is sorted to provide a consistent hash (and the underlying rules are not changing), the `Config` is presumably static / defined by flags on the `prometheus-operator`, and running a diff on the `Prometheus` resource as returned by `kubectl` shows no changes.

Since the entire `Prometheus` object is included in the hash, and the main `Prometheus` resource shows no changes, it must be the `PrometheusStatus` subresource which is changing. Of course, since I'm still running K8s 1.9.x, I don't have access to the `CustomResourceSubresources` feature gate required to verify that...

**Comment by mxinden** [comment]
@Capitrium I hope I understand your suspicion correctly: as far as I know, updating the status of a Kubernetes object enforces the resource version to change. That would trigger an event increasing the `prometheus_operator_triggered_total` with the `prometheus` label, which seems to be not the case according to your screenshot above.

Just to make sure, would you mind checking if the ResourceVersion of the Prometheus custom resource is also frequently changing?

---

> I've spun up a second cluster with a much smaller set of alerting rules, and it does not show this issue

How many PrometheusRule custom resources are on the initial cluster? Are they extraordinary large?

This sounds promising. I tried this out locally with 1000 Rule custom resources, but couldn't see the same issue.

**Comment by mxinden** [comment]
@Capitrium In addition would you mind increasing the log level on the Prometheus Operator (`--log-level=all`) and post the logs here?

**Comment by Capitrium** [comment]
@mxinden I believe you're right; the `resourceVersion` isn't changing on any of the Prometheus, PrometheusRule, or ConfigMap resources, so my suspicion was incorrect.

There are 16 PrometheusRule resources associated with the broken `k8s` Prometheus cluster, none of which is particularly large; the largest is ~9kb, and the combined ConfigMap of all rules is ~32kb.

Here's the `sync prometheus` section of the logs that gets repeated several times per second, with `--log-level=all`:
```
level=info ts=2018-08-03T16:40:01.020410912Z caller=operator.go:883 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=debug ts=2018-08-03T16:40:01.020452955Z caller=rule_configmap_migration.go:43 component=prometheusoperator msg="selected rule configmaps for migration" configmaps= namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.020468332Z caller=rule_configmap_migration.go:63 component=prometheusoperator msg="rule files to be created" rules= namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.020480246Z caller=rule_configmap_migration.go:84 component=prometheusoperator msg="rule files created successfully" namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.020493367Z caller=rules.go:150 component=prometheusoperator msg="selected RuleNamespaces" namespaces=monitoring namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.025907476Z caller=rules.go:192 component=prometheusoperator msg="selected Rules" rules=monitoring-prometheus-k8s-rules-kube-controller-manager.rules.yaml.yaml,monitoring-prometheus-k8s-rules-kubernetes.rules.yaml.yaml,monitoring-prometheus-k8s-rules-infrastructure.rules.yaml,monitoring-prometheus-k8s-rules-autoscaling.rules.yaml.yaml,monitoring-prometheus-k8s-rules-general.rules.yaml.yaml,monitoring-prometheus-k8s-rules-graylog2.rules.yaml,monitoring-prometheus-k8s-rules-kubelet.rules.yaml.yaml,monitoring-prometheus-k8s-rules-prometheus.rules.yaml.yaml,monitoring-prometheus-k8s-rules-node.rules.yaml.yaml,monitoring-prometheus-k8s-rules-kube-state-metrics.rules.yaml.yaml,monitoring-prometheus-k8s-rules-alertmanager.rules.yaml.yaml,monitoring-prometheus-k8s-rules-imposium.rules.yaml,monitoring-prometheus-k8s-rules-kube-scheduler.rules.yaml.yaml,monitoring-prometheus-k8s-rules-vault.rules.yaml,monitoring-prometheus-k8s-rules-rabbitmq.rules.yaml,monitoring-prometheus-k8s-rules-etcd3.rules.yaml.yaml namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.068782548Z caller=rules.go:68 component=prometheusoperator msg="no PrometheusRule changes" namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.068850407Z caller=operator.go:1270 component=prometheusoperator msg="filtering namespaces to select ServiceMonitors from" namespaces=monitoring namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.068902142Z caller=operator.go:1285 component=prometheusoperator msg="selected ServiceMonitors" servicemonitors=monitoring/imposium-pushgateway-staging,monitoring/rabbitmq,monitoring/vault,monitoring/kube-apiserver,monitoring/alertmanager,monitoring/kube-dns,monitoring/vault-controller,monitoring/node-exporter,monitoring/etcd,monitoring/kube-state-metrics,monitoring/linkerd,monitoring/kubelet,monitoring/cluster-autoscaler,monitoring/kube-controller-manager,monitoring/prometheus,monitoring/etcd-events,monitoring/kube-scheduler,monitoring/aws-accountant,monitoring/graylog,monitoring/aws-audit-exporter,monitoring/ad-uploader,monitoring/prometheus-operator namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.126623439Z caller=operator.go:1233 component=prometheusoperator msg="updating Prometheus configuration secret skipped, no configuration change"
level=debug ts=2018-08-03T16:40:01.142886157Z caller=operator.go:962 component=prometheusoperator msg="updating current Prometheus statefulset"
level=debug ts=2018-08-03T16:40:01.151462725Z caller=operator.go:852 component=prometheusoperator msg="update handler" old=464354601 cur=464354602
level=debug ts=2018-08-03T16:40:01.151519658Z caller=operator.go:861 component=prometheusoperator msg="StatefulSet updated"
level=info ts=2018-08-03T16:40:01.151722525Z caller=operator.go:883 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=debug ts=2018-08-03T16:40:01.151800893Z caller=rule_configmap_migration.go:43 component=prometheusoperator msg="selected rule configmaps for migration" configmaps= namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.151829078Z caller=rule_configmap_migration.go:63 component=prometheusoperator msg="rule files to be created" rules= namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.15184283Z caller=rule_configmap_migration.go:84 component=prometheusoperator msg="rule files created successfully" namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.15186095Z caller=rules.go:150 component=prometheusoperator msg="selected RuleNamespaces" namespaces=monitoring namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.210657979Z caller=operator.go:366 component=alertmanageroperator msg="update handler" old=464354601 cur=464354602
level=debug ts=2018-08-03T16:40:01.215460067Z caller=rules.go:192 component=prometheusoperator msg="selected Rules" rules=monitoring-prometheus-k8s-rules-etcd3.rules.yaml.yaml,monitoring-prometheus-k8s-rules-imposium.rules.yaml,monitoring-prometheus-k8s-rules-kubernetes.rules.yaml.yaml,monitoring-prometheus-k8s-rules-autoscaling.rules.yaml.yaml,monitoring-prometheus-k8s-rules-kube-state-metrics.rules.yaml.yaml,monitoring-prometheus-k8s-rules-infrastructure.rules.yaml,monitoring-prometheus-k8s-rules-alertmanager.rules.yaml.yaml,monitoring-prometheus-k8s-rules-kube-controller-manager.rules.yaml.yaml,monitoring-prometheus-k8s-rules-prometheus.rules.yaml.yaml,monitoring-prometheus-k8s-rules-rabbitmq.rules.yaml,monitoring-prometheus-k8s-rules-vault.rules.yaml,monitoring-prometheus-k8s-rules-node.rules.yaml.yaml,monitoring-prometheus-k8s-rules-kubelet.rules.yaml.yaml,monitoring-prometheus-k8s-rules-graylog2.rules.yaml,monitoring-prometheus-k8s-rules-kube-scheduler.rules.yaml.yaml,monitoring-prometheus-k8s-rules-general.rules.yaml.yaml namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.2565817Z caller=rules.go:68 component=prometheusoperator msg="no PrometheusRule changes" namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.256612997Z caller=operator.go:1270 component=prometheusoperator msg="filtering namespaces to select ServiceMonitors from" namespaces=monitoring namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.256660413Z caller=operator.go:1285 component=prometheusoperator msg="selected ServiceMonitors" servicemonitors=monitoring/graylog,monitoring/vault-controller,monitoring/prometheus,monitoring/vault,monitoring/linkerd,monitoring/ad-uploader,monitoring/etcd-events,monitoring/kube-scheduler,monitoring/etcd,monitoring/imposium-pushgateway-staging,monitoring/kube-state-metrics,monitoring/kube-apiserver,monitoring/aws-audit-exporter,monitoring/kube-controller-manager,monitoring/rabbitmq,monitoring/kube-dns,monitoring/kubelet,monitoring/aws-accountant,monitoring/node-exporter,monitoring/cluster-autoscaler,monitoring/alertmanager,monitoring/prometheus-operator namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.423103642Z caller=operator.go:1233 component=prometheusoperator msg="updating Prometheus configuration secret skipped, no configuration change"
level=debug ts=2018-08-03T16:40:01.439271618Z caller=operator.go:962 component=prometheusoperator msg="updating current Prometheus statefulset"
level=debug ts=2018-08-03T16:40:01.447475849Z caller=operator.go:660 component=prometheusoperator msg="ConfigMap updated"
level=debug ts=2018-08-03T16:40:01.44788499Z caller=operator.go:852 component=prometheusoperator msg="update handler" old=464354602 cur=464354603
level=debug ts=2018-08-03T16:40:01.447926578Z caller=operator.go:861 component=prometheusoperator msg="StatefulSet updated"
level=info ts=2018-08-03T16:40:01.447945867Z caller=operator.go:883 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=debug ts=2018-08-03T16:40:01.44798049Z caller=rule_configmap_migration.go:43 component=prometheusoperator msg="selected rule configmaps for migration" configmaps= namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.447994158Z caller=rule_configmap_migration.go:63 component=prometheusoperator msg="rule files to be created" rules= namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.448004547Z caller=rule_configmap_migration.go:84 component=prometheusoperator msg="rule files created successfully" namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.448016051Z caller=rules.go:150 component=prometheusoperator msg="selected RuleNamespaces" namespaces=monitoring namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.448028093Z caller=operator.go:366 component=alertmanageroperator msg="update handler" old=464354602 cur=464354603
level=debug ts=2018-08-03T16:40:01.453265523Z caller=rules.go:192 component=prometheusoperator msg="selected Rules" rules=monitoring-prometheus-k8s-rules-rabbitmq.rules.yaml,monitoring-prometheus-k8s-rules-kube-state-metrics.rules.yaml.yaml,monitoring-prometheus-k8s-rules-kubernetes.rules.yaml.yaml,monitoring-prometheus-k8s-rules-infrastructure.rules.yaml,monitoring-prometheus-k8s-rules-general.rules.yaml.yaml,monitoring-prometheus-k8s-rules-kubelet.rules.yaml.yaml,monitoring-prometheus-k8s-rules-graylog2.rules.yaml,monitoring-prometheus-k8s-rules-autoscaling.rules.yaml.yaml,monitoring-prometheus-k8s-rules-imposium.rules.yaml,monitoring-prometheus-k8s-rules-kube-controller-manager.rules.yaml.yaml,monitoring-prometheus-k8s-rules-etcd3.rules.yaml.yaml,monitoring-prometheus-k8s-rules-alertmanager.rules.yaml.yaml,monitoring-prometheus-k8s-rules-vault.rules.yaml,monitoring-prometheus-k8s-rules-kube-scheduler.rules.yaml.yaml,monitoring-prometheus-k8s-rules-node.rules.yaml.yaml,monitoring-prometheus-k8s-rules-prometheus.rules.yaml.yaml namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.494711023Z caller=rules.go:68 component=prometheusoperator msg="no PrometheusRule changes" namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.494764503Z caller=operator.go:1270 component=prometheusoperator msg="filtering namespaces to select ServiceMonitors from" namespaces=monitoring namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.494820518Z caller=operator.go:1285 component=prometheusoperator msg="selected ServiceMonitors" servicemonitors=monitoring/kube-scheduler,monitoring/cluster-autoscaler,monitoring/alertmanager,monitoring/kubelet,monitoring/kube-state-metrics,monitoring/imposium-pushgateway-staging,monitoring/kube-dns,monitoring/node-exporter,monitoring/aws-audit-exporter,monitoring/etcd-events,monitoring/etcd,monitoring/rabbitmq,monitoring/vault-controller,monitoring/linkerd,monitoring/kube-apiserver,monitoring/prometheus,monitoring/prometheus-operator,monitoring/kube-controller-manager,monitoring/graylog,monitoring/aws-accountant,monitoring/vault,monitoring/ad-uploader namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.527899585Z caller=operator.go:1233 component=prometheusoperator msg="updating Prometheus configuration secret skipped, no configuration change"
level=debug ts=2018-08-03T16:40:01.545676374Z caller=operator.go:962 component=prometheusoperator msg="updating current Prometheus statefulset"
level=debug ts=2018-08-03T16:40:01.616688521Z caller=operator.go:366 component=alertmanageroperator msg="update handler" old=464354603 cur=464354605
level=debug ts=2018-08-03T16:40:01.617173284Z caller=operator.go:852 component=prometheusoperator msg="update handler" old=464354603 cur=464354605
level=debug ts=2018-08-03T16:40:01.617250658Z caller=operator.go:861 component=prometheusoperator msg="StatefulSet updated"
level=info ts=2018-08-03T16:40:01.61728003Z caller=operator.go:883 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=debug ts=2018-08-03T16:40:01.617330196Z caller=rule_configmap_migration.go:43 component=prometheusoperator msg="selected rule configmaps for migration" configmaps= namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.617377115Z caller=rule_configmap_migration.go:63 component=prometheusoperator msg="rule files to be created" rules= namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.617391161Z caller=rule_configmap_migration.go:84 component=prometheusoperator msg="rule files created successfully" namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.617405307Z caller=rules.go:150 component=prometheusoperator msg="selected RuleNamespaces" namespaces=monitoring namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.623082159Z caller=rules.go:192 component=prometheusoperator msg="selected Rules" rules=monitoring-prometheus-k8s-rules-kube-scheduler.rules.yaml.yaml,monitoring-prometheus-k8s-rules-prometheus.rules.yaml.yaml,monitoring-prometheus-k8s-rules-vault.rules.yaml,monitoring-prometheus-k8s-rules-general.rules.yaml.yaml,monitoring-prometheus-k8s-rules-rabbitmq.rules.yaml,monitoring-prometheus-k8s-rules-infrastructure.rules.yaml,monitoring-prometheus-k8s-rules-kube-controller-manager.rules.yaml.yaml,monitoring-prometheus-k8s-rules-kube-state-metrics.rules.yaml.yaml,monitoring-prometheus-k8s-rules-kubernetes.rules.yaml.yaml,monitoring-prometheus-k8s-rules-kubelet.rules.yaml.yaml,monitoring-prometheus-k8s-rules-alertmanager.rules.yaml.yaml,monitoring-prometheus-k8s-rules-etcd3.rules.yaml.yaml,monitoring-prometheus-k8s-rules-imposium.rules.yaml,monitoring-prometheus-k8s-rules-graylog2.rules.yaml,monitoring-prometheus-k8s-rules-node.rules.yaml.yaml,monitoring-prometheus-k8s-rules-autoscaling.rules.yaml.yaml namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.691294564Z caller=rules.go:68 component=prometheusoperator msg="no PrometheusRule changes" namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.69137098Z caller=operator.go:1270 component=prometheusoperator msg="filtering namespaces to select ServiceMonitors from" namespaces=monitoring namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.691448045Z caller=operator.go:1285 component=prometheusoperator msg="selected ServiceMonitors" servicemonitors=monitoring/kube-controller-manager,monitoring/cluster-autoscaler,monitoring/aws-accountant,monitoring/prometheus-operator,monitoring/aws-audit-exporter,monitoring/kube-state-metrics,monitoring/prometheus,monitoring/vault,monitoring/kubelet,monitoring/etcd,monitoring/kube-scheduler,monitoring/ad-uploader,monitoring/alertmanager,monitoring/kube-dns,monitoring/node-exporter,monitoring/rabbitmq,monitoring/graylog,monitoring/linkerd,monitoring/vault-controller,monitoring/etcd-events,monitoring/imposium-pushgateway-staging,monitoring/kube-apiserver namespace=monitoring prometheus=k8s
level=debug ts=2018-08-03T16:40:01.743118198Z caller=operator.go:1233 component=prometheusoperator msg="updating Prometheus configuration secret skipped, no configuration change"
level=debug ts=2018-08-03T16:40:01.811103701Z caller=operator.go:962 component=prometheusoperator msg="updating current Prometheus statefulset"
level=debug ts=2018-08-03T16:40:01.821851272Z caller=operator.go:852 component=prometheusoperator msg="update handler" old=464354605 cur=464354607
level=debug ts=2018-08-03T16:40:01.821931347Z caller=operator.go:861 component=prometheusoperator msg="StatefulSet updated"
level=info ts=2018-08-03T16:40:01.821957004Z caller=operator.go:883 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
```

**Comment by brancz** [comment]
Would it be possible for you to share all your ServiceMonitor and PrometheusRule objects with us? That would probably help us reproduce this.

**Comment by mxinden** [comment]
@Capitrium thanks for posting the logs.

The pattern that I see is that both creating the rules ConfigMap as well as the configuration Secret is skipped, as there are no changes, still the Prometheus StatefulSet is updated. This is in line with the high update rate shown in your [comment](https://github.com/coreos/prometheus-operator/issues/1659#issuecomment-409589928), but leaves us wondering why the ConfigMap counter is growing so fast.

According to the [metrics above](https://github.com/coreos/prometheus-operator/issues/1659#issuecomment-409589928) and the logs, the rule ConfigMap, the configuration Secret, as well as the Prometheus custom resource is not changing frequently.

I will look into Prometheus StatefulSet generation and check  where it is not deterministic.

**Comment by Capitrium** [comment]
@mxinden @brancz After playing around with every combination of ServiceMonitor / PrometheusRule change I could imagine, I was finally able to reproduce this in minikube by doing something pretty much completely unrelated:

1) Deploy the kube-prometheus stack to minikube
2) Annotate the prometheus k8s object:
```
kubectl annotate prometheus -n monitoring k8s test-annotation=test-value 
```
3) prometheus-operator syncs k8s object multiple times per second

It seems like even the existence of the `annotations` metadata field breaks the hashing; running `kubectl annotate prometheus -n monitoring k8s test-annotation-` results in a blank annotations field (`annotations: {}`) and the operator still syncs excessively. Removing the annotations field from the prometheus object entirely stops the excessive syncing.

This came up since I frequently use `kubectl apply`, which adds the `last-applied-configuration` annotation; hopefully you get the same results in your tests... :laughing:

**Comment by mxinden** [comment]
Great news! Will test this out after the weekend. Thanks for debugging!

**Comment by mxinden** [comment]
I am able to reproduce the issue now. https://github.com/coreos/prometheus-operator/pull/1785 contains both a test to prevent regressions as well as a fix.

@Capitrium would you mind testing this out once again? Let me know if you want me to push a docker image. Thanks a lot for making this reproducible! Great job.

**Comment by mxinden** [comment]
@Capitrium in case it is more convenient: `quay.io/mxinden/prometheus-operator:high-cpu-usage-v1`

**Comment by Capitrium** [comment]
@mxinden yep, I've confirmed that the issue is fixed using the `high-cpu-usage-v1` image! Thanks for the quick fix - looking forward to the next release 😄

**Comment by iftachsc** [comment]
+1 still seeing this on latest prometheus-operator stable chart. it is syncing 3-4 times every second

**Comment by domino7** [comment]
I also observed that issue recently: 
```
Prometheus v2.7.1
Prometheus Operator v0.29.0
```
```
level=info ts=2019-02-21T17:13:51.808639305Z caller=operator.go:970 component=prometheusoperator msg="sync prometheus" key=openshift-monitoring/k8s
level=info ts=2019-02-21T17:13:51.84822738Z caller=operator.go:970 component=prometheusoperator msg="sync prometheus" key=abc-metrics-prometheus/abc
level=info ts=2019-02-21T17:13:51.893857024Z caller=operator.go:970 component=prometheusoperator msg="sync prometheus" key=openshift-monitoring/k8s
level=info ts=2019-02-21T17:13:51.948613556Z caller=operator.go:970 component=prometheusoperator msg="sync prometheus" key=abc-metrics-prometheus/abc
```
The same happens to all related resources (configmaps, statefulsets, secrets, prometheusrules, servicemonitors)

Adding test annotation / removing "last-applied-configuration" annotation (as described above) is not changing operator behavior, resyncPeriod configured in Operator is not taken into account. That leads to enormous number of Kubernetes API calls and cluster stability issues.

Test setup was monitoring entire cluster with:
- operator namespaces flag set to: NamespaceAll
- prometheus intance with limited acess the few namespaces in openhift-monitoring project
- custom prometheus instance monitoring entire cluster with:

```
ruleNamespaceSelector:
  any: true
serviceMonitorNamespaceSelector:
  any: true
```

**Temporal solution**
I was able to limit api calls by configuring separate Prometheus namespace flag for operator (appplied also for Alertmanager sync) - in similarity to coreos#2197  and addidng additonal trottling interval in code - all changes in https://github.com/SabreOSS/prometheus-operator/commit/9955a8038236d7ffc3215e5a3af0dc1acc612267. That chanages reduced API calls by 2 orders of magnitude.

Any further help to stabilize setup / find main reason of that behavior and accept PR with additional flag to limit Prometheus and Alertmanager namespaces will be appreciated.

**Comment by brancz** [comment]
The namespace selectors you have configured don't look right, those objects are full kubernetes labelselectors so they have to follow the `matchLabels` and `matchExpressions` schema.

**Comment by iftachsc** [comment]
isnt there any way to control the sync interval? this actually makes my prometheus-operator namespace takes allot of resources relatively. beside our workloads namespaces it is the highest consuming cpu namespace (shown in prometheus) - with no reason.

**Comment by domino7** [comment]
@brancz selecting all namespaces with `any: true` for `ruleNamespaceSelector` and `serviceMonitorNamespaceSelector` is valid use case and keeps consistency with `NamespaceSelector` in `ServiceMonitorSpec` and `NamespaceAll` flag in Operator config (in terms of monitoring entire cluster). I already tested it, rules/service monitors are added from all projects correctly. From that perspective that config should be officially supported and added to API docs.

@iftachsc I observed same behavior, sync interval is configured with `resyncPeriod`: https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/operator.go#L54, unfortunately, as we both observed, it's not taken into account in some use cases.

**Comment by kamikaze** [comment]
got the same issue today with kube-prometheus-stack 52.1.0

**Comment by xsoheilalizadeh** [comment]
I have this issue constantly while using kube-prometheus-stack chart

**Comment by kamikaze** [comment]
> I have this issue constantly while using kube-prometheus-stack chart

For me it was when multiple gitlab-agent helm charts have been deployed. For a single one - there was no issue. Do you have any helm chart installed for multiple times?
