### ISSUE TITLE
prometheus-config-reloader, rules-configmap-reloader alertmanager config-reloader have insufficient CPU resources

### ISSUE THREAD

**Issue by paskal** [coreos/prometheus-operator#2171]
Moving https://github.com/helm/charts/issues/9540 issue there.
**What did you do?**
`helm install stable/prometheus-operator` with https://github.com/helm/charts/pull/9516 patch applied (actual alerts state sync) on GKE cluster

**What did you expect to see?**
No alerts on prometheus-operator itself.

**What did you see instead? Under which circumstances?**
Following alerts in Prometheus:

>message
>    41% throttling of CPU in namespace monitoring for container prometheus-config-reloader in pod prometheus-operator-prometheus-0.

>message
>    33% throttling of CPU in namespace monitoring for container rules-configmap-reloader in pod prometheus-operator-prometheus-0.

> message
>    39% throttling of CPU in namespace monitoring for container config-reloader in pod alertmanager-prometheus-operator-alertmanager-0.

**Environment**

* Prometheus Operator version:

`v0.25.0`

* Kubernetes version information:

```
➜  ~  kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:16Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.11", GitCommit:"42df8ec7aef509caba40b6178616dcffca9d7355", GitTreeState:"clean", BuildDate:"2018-11-08T20:06:00Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: 

`GKE`

**Anything else we need to know**:
It seems like limits for this pod are not enough and should be increased:
```
    name: rules-configmap-reloader
    resources:
      limits:
        cpu: 5m
        memory: 10Mi
      requests:
        cpu: 5m
        memory: 10Mi
---
    name: prometheus-config-reloader
    resources:
      limits:
        cpu: 10m
        memory: 50Mi
      requests:
        cpu: 10m
        memory: 50Mi
---
    name: config-reloader
    resources:
      limits:
        cpu: 5m
        memory: 10Mi
      requests:
        cpu: 5m
        memory: 10Mi
```
Other possible case is busy loop, in this case no resources will be enough. But these limits are really low and I guess just increasing the value should help.

**Comment by brancz** [comment]
This is being fixed with #2144.

**Comment by paskal** [comment]
Thanks! Resolving then.

**Comment by rdubya16** [comment]
@brancz Should this fix resolve config-reloader? I applied these diffs to my cluster and im still getting this:

`alertname="CPUThrottlingHigh" container_name="config-reloader" namespace="monitoring" pod_name="alertmanager-main-1" severity="warning" 60.00000000000001`

**Comment by brancz** [comment]
cc @metalmatze ^

**Comment by metalmatze** [comment]
Yes, the PR linked above was also about the config-reloader for Alertmanager. See [here](https://github.com/coreos/prometheus-operator/pull/2144/files#diff-12bb2598410d9abb923f48dac5890760R462)
It seems that this was still not enough, but it really should be now. Is your cluster under a lot of load?

Otherwise I guess I can only tell you to silence this specific alert for now.

**Comment by pgporada** [comment]
I see this often in my clusters running the helm version of prometheus-operator.

```
100 * sum by(container_name, pod_name, namespace) (increase(container_cpu_cfs_throttled_periods_total{container_name!=""}[5m])) / sum by(container_name, pod_name, namespace) (increase(container_cpu_cfs_periods_total[5m])) > 30

{container_name="rules-configmap-reloader",namespace="monitoring",pod_name="prometheus-prometheus-operator-prometheus-0"}	33.33333333333333
{container_name="config-reloader",namespace="monitoring",pod_name="alertmanager-prometheus-operator-alertmanager-0"}	57.142857142857146
```

```
$ helm ls
NAME               	REVISION	UPDATED                 	STATUS  	CHART                    	APP VERSION	NAMESPACE
prometheus-operator	38      	Thu Jan 31 18:39:28 2019	DEPLOYED	prometheus-operator-2.1.2	0.26.0     	monitoring
...
```

I was under the impression that https://github.com/helm/charts/issues/9540 and https://github.com/coreos/prometheus-operator/pull/2144 should have upped the limits for at least the alertmanager config-reloader, but here's what my cluster shows.
```
$ kubectl describe pod prometheus-prometheus-operator-prometheus-0 -n monitoring
...
  prometheus-config-reloader:
    Image:         quay.io/coreos/prometheus-config-reloader:v0.25.0
    Limits:
      cpu:     10m
      memory:  50Mi
    Requests:
      cpu:     10m
      memory:  50Mi
...
  rules-configmap-reloader:
    Image:         quay.io/coreos/configmap-reload:v0.0.1
    Limits:
      cpu:     5m
      memory:  10Mi
    Requests:
      cpu:        5m
      memory:     10Mi
...

$ kubectl describe pod alertmanager-prometheus-operator-alertmanager-0 -n monitoring
...
  config-reloader:
    Image:         quay.io/coreos/configmap-reload:v0.0.1
    Limits:
      cpu:     5m
      memory:  10Mi
    Requests:
      cpu:        5m
      memory:     10Mi
...
```

My cluster isn't even half utilized according to https://github.com/etopeter/kubectl-view-utilization
```
$ ./kubectl-view-utilization.sh
cores     11 / 24    (46%)
memory   13G / 45G   (28%)
```

**Comment by tpolekhin** [comment]
Im seeing a similar picture even with updated limits in my cluster
```
kubectl -n monitoring describe po prometheus-monitoring-prometheus-oper-prometheus-0
...
  prometheus-config-reloader:
    Image:         quay.io/coreos/prometheus-config-reloader:v0.26.0
    Limits:
      cpu:     50m
      memory:  50Mi
    Requests:
      cpu:     50m
      memory:  50Mi
...
  rules-configmap-reloader:
    Image:         quay.io/coreos/configmap-reload:v0.0.1
    Limits:
      cpu:     25m
      memory:  10Mi
    Requests:
      cpu:        25m
      memory:     10Mi
```
```
kubectl -n monitoring describe po alertmanager-monitoring-prometheus-oper-alertmanager-0
...
  config-reloader:
    Image:         quay.io/coreos/configmap-reload:v0.0.1
    Limits:
      cpu:     50m
      memory:  10Mi
    Requests:
      cpu:        50m
      memory:     10Mi
```
![pod_throttling_high](https://user-images.githubusercontent.com/10550832/52489141-27a4a300-2bca-11e9-81da-91def6325fa0.png)

**Comment by pgporada** [comment]
@tpolekhin May I ask how you increased the limit and requests for those pods?

**Comment by tpolekhin** [comment]
@pgporada my version of operator has this https://github.com/coreos/prometheus-operator/pull/2144 merged
i did not increased limits myself, afaik its not possible
my comment was indicating that even after limits were increased we still see CPUTrottling alerts on these containers

**Comment by paskal** [comment]
I'm sorry, but could someone verify these containers aren't running in busy loop, e.g. aren't they will consume all CPU possible no matter what's the limit? @brancz, could you please cast relevant developer into this issue?

**Comment by brancz** [comment]
v0.29.0 has been released that both bumps the default and makes this configurable via the flags.

**Comment by paskal** [comment]
@brancz, thanks! 0.29.0 seems to fix the problem, [prometheus-operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator) 3.0.0+ goes with this version. Resolving this issue.

**Comment by eduardobaitello** [comment]
I'm using the prometheus-operator helm chart v3.0.0, and the `CPUThrottlingHigh` alert is entering in `PENDING` state for the reloader containers intermittently. It lasts about 5m, so they are not firing at all.

_Off-topic: I'm having trouble with another containers, there is a way to silence notifications for this alert using config files from prometheus-operator chart? If so, help me [here](https://stackoverflow.com/q/54806336/7641078), please :)_

**Comment by dimm0** [comment]
I deployed the new 0.29.0, and I get throttling alert from every single pod in monitoring namespace

**Comment by aleclerc** [comment]
Also hitting intermittent (but quite frequent) alerts for config-reloader. Upgrading to Helm chart v4.0.0. (using 0.29.0) but doesn't seem to help anything.

**Comment by JessieAMorris** [comment]
Same, the CPUThrottlingHigh alert is still happening. Could we get a way to be able to set thresholds for the kubernetes-mixin alerts?

**Comment by mshivanna** [comment]
we just deployed the latest version prometheus-operator-4.3.3. and we still see this issue.

![image](https://user-images.githubusercontent.com/2934982/55262668-e41efa80-5244-11e9-974e-de1580b078dc.png)

**Comment by JessieAMorris** [comment]
@mshivanna This is really more an issue with the prometheus-operator chart.

https://github.com/helm/charts/issues/11768

That issue was created for this, but the config flag was only setup for one of two containers in the pod. 

I created a PR in prometheus operator (https://github.com/coreos/prometheus-operator/pull/2466) that fixes this. Once a release of prometheus-operator is done and the helm chart is pointed at that app version this should be resolved.

**Comment by mshivanna** [comment]
ok makes sense @JessieAMorris thanks for the clarification

**Comment by dimm0** [comment]
I'm not using the helm chart, seeing the same issues

**Comment by alejandrox1** [comment]
Seeing the same problem as in the latest comments so i opened https://github.com/coreos/prometheus-operator/issues/2575
the problem, i think, is that the flag to specify the resource limits only works in the `rules-configmap-reloader` container but not in the `prometheus-config-reloader` container within the prometheus-operator pod.
