### ISSUE TITLE
Alertmanager and Prometheus CrashLoopBackOff

### ISSUE THREAD

**Issue by agusl88** [coreos/prometheus-operator#2948]
**What did you do?**

Deploying prometheus-operator using the latest helm chart on EKS 1.14 results in the following error:

```
prometheus-prometheus-operator-prometheus-0 prometheus-config-reloader level=error ts=2020-01-10T14:24:46.022632354Z caller=runutil.go:87 msg="function failed. Retrying in next tick" err="trigger reload: reload request failed: Post http://127.0.0.1:9090/-/reload: dial tcp 127.0.0.1:9090: connect: connection refused"
```
```
> NAME                                                              READY   STATUS             RESTARTS   AGE
> alertmanager-prometheus-operator-alertmanager-0                   1/2     CrashLoopBackOff   227        18h
> prometheus-prometheus-operator-prometheus-0                       2/3     CrashLoopBackOff   5          5m15s
```
I saw this error reported on #2413, the suggestion was to update prometheus-operator to v0.29, but i'm already on v0.34. According to #2409 the root cause of the problem was the memory limit of 10Mi on the reloader pod, but looking at the current manifest the memory is already set to 25mi.

Couldn't find any other errors on the logs, the event log looks normal. 

* Prometheus Operator version: 0.34

* Kubernetes version information: 1.14.7

* Kubernetes cluster kind: EKS 

* Helm chart version: 8.5.4

* Helm version: 3.0.2

**Comment by metalmatze** [comment]
This was fixed in a recent PR but not yet released: https://github.com/coreos/prometheus-operator/pull/2929.

**Comment by agusl88** [comment]
Changed the prometheus-operator deployment to use the image tagged as master that already has the fix, but the problem persist. Am I missing something?

> kubectl set image deployment/prometheus-operator-operator prometheus-operator=quay.io/coreos/prometheus-operator:master

**Comment by metalmatze** [comment]
What do you see when `kubectl describe`ing one of the Prometheus Pods, does it have events that fail the probes?

**Comment by agusl88** [comment]
Event log from the prometheus pod: 

`Events:
  Type     Reason     Age                From                                                 Message
  ----     ------     ----               ----                                                 -------
  Normal   Scheduled  46s                default-scheduler                                    Successfully assigned default/prometheus-prometheus-operator-prometheus-0 to ip-10-0-103-220.us-east-2.compute.internal
  Normal   Pulled     43s                kubelet, ip-10-0-103-220.us-east-2.compute.internal  Container image "quay.io/coreos/prometheus-config-reloader:v0.34.0" already present on machine
  Normal   Pulled     42s                kubelet, ip-10-0-103-220.us-east-2.compute.internal  Container image "quay.io/coreos/configmap-reload:v0.0.1" already present on machine
  Normal   Created    42s                kubelet, ip-10-0-103-220.us-east-2.compute.internal  Created container rules-configmap-reloader
  Normal   Started    42s                kubelet, ip-10-0-103-220.us-east-2.compute.internal  Started container rules-configmap-reloader
  Normal   Created    42s                kubelet, ip-10-0-103-220.us-east-2.compute.internal  Created container prometheus-config-reloader
  Normal   Started    42s                kubelet, ip-10-0-103-220.us-east-2.compute.internal  Started container prometheus-config-reloader
  Normal   Pulled     24s (x3 over 43s)  kubelet, ip-10-0-103-220.us-east-2.compute.internal  Container image "quay.io/prometheus/prometheus:v2.13.1" already present on machine
  Normal   Created    24s (x3 over 43s)  kubelet, ip-10-0-103-220.us-east-2.compute.internal  Created container prometheus
  Normal   Started    23s (x3 over 43s)  kubelet, ip-10-0-103-220.us-east-2.compute.internal  Started container prometheus
  Warning  BackOff    4s (x6 over 40s)   kubelet, ip-10-0-103-220.us-east-2.compute.internal  Back-off restarting failed container`

**Comment by agusl88** [comment]
One thing worth mention, **listenLocal** is set to **false** (is the default value for the helm chart). The problem described on the PR you made reference (#2929) seems to be only present when **listenLocal** is set to **true**.

**Comment by mizhkeao** [comment]
I'm running into the same issue. @agusl88 were you able to solve this issue?
