### ISSUE TITLE
Add README for kube-prometheus helm chart

### ISSUE THREAD

**Issue by ryanwalls** [coreos/prometheus-operator#513]
Would love to have a README with a couple examples of how to get the `kube-prometheus` helm chart running successfully.  

Something similar to: https://github.com/coreos/prometheus-operator/blob/master/helm/prometheus/README.md

**Comment by gianrubio** [comment]
@ryanwalls I had the same issue on the first time I deployed kube-prometheus. I'm pretty sure this is related to https://github.com/coreos/prometheus-operator/issues/443#issuecomment-311046540.

Could you try to reinstall prometheus with the right `serviceMonitorSelector`?

```
helm install --name prometheus --set serviceMonitorsSelector.app=prometheus prometheus
```

**Comment by ryanwalls** [comment]
@gianrubio Which issue are you referring to?

Also, I'm using the `kube-prometheus` chart, so I'm not explicitly installing the `prometheus` chart.

**Comment by burdiyan** [comment]
Does anyone managed to install kube-prometheus chart? I alway have an error of: `Error: apiVersion "monitoring.coreos.com/v1" in kube-prometheus/charts/exporter-kubernetes/templates/servicemonitor.yaml is not available`

**Comment by gianrubio** [comment]
@burdiyan it's your first time running the charts? If the answer is not, you probably have some garbage from previous version.

I would recommend you to:
-  Purge the charts running: ``` helm delete --purge chart-name````
-  Remove all the `crd or thirdypartyresource`.

```
kubectl delete crd (or thirdypartyresource) prometheuses.monitoring.coreos.com 
kubectl delete crd (or thirdypartyresource) servicemonitors.monitoring.coreos.com 
kubectl delete crd (or thirdypartyresource) alertmanagers.monitoring.coreos.com
```
- Reinstall the chart

let me know if this fix you setup.

**Comment by burdiyan** [comment]
@gianrubio That was my first attempt to install the chart in a brand new GKE cluster.

**Comment by gianrubio** [comment]
Do you have prometheus-operator installed? Try to install it first and after that install kube-prometheus.

Also please post the output of

```kubectl get pods,jobs -n monitoring```

**Comment by burdiyan** [comment]
@gianrubio Yeah, that was the error, and I just figured out that you have to install the operator first. Worth mentioning on the README of `kube-prometheus` chart I believe.

Thanks a lot, anyway!

**Comment by brancz** [comment]
Does someone want to add a troubleshooting section or something to the helm readme? Maybe we can add some examples as well, as suggested in the beginning of the thread.

**Comment by gianrubio** [comment]
I can do it after all the rework on helm, btw I mapped this dependency on my [todo list](https://github.com/coreos/prometheus-operator/issues/592#issuecomment-346468179)

**Comment by mbenabda** [comment]
@burdiyan you seem to have experienced the same problem i did: are you using quay.io/coreos/prometheus-operator:v0.11.3 on k8s 1.6.x ?
if that's the case, then this PR should solve it: https://github.com/coreos/prometheus-operator/pull/829

**Comment by odino** [comment]
@gianrubio how does it work that one's supposed to install the operathor first to then install kube-prometheus? I though [this chart dependency[(https://github.com/coreos/prometheus-operator/blob/master/helm/kube-prometheus/requirements.yaml#L7-L10) would take care of that

**Comment by burdiyan** [comment]
@odino I guess master branch is not yet published to the CoreOS chart repository, and in previous versions this requirement was not there yet.

**Comment by odino** [comment]
gotcha!

**Comment by brancz** [comment]
This should now be fixed, we are now automatically uploading new versions as they are bumped and merged.

**Comment by jordanjennings** [comment]
@brancz Thanks for getting the latest versions synced up! Can this issue remain open until the original concern is addressed of adding information to the readme on how to actually use the charts? I'm installing via the scripts right now and would prefer to move to the chart but not really sure how to do it.

**Comment by brancz** [comment]
Thanks for your response. I’m fine with re-opening for that purpose.

**Comment by vsliouniaev** [comment]
@jordanjennings There is an official helm chart that can be deployed all in one go now. It may still require some documentation to be complete, but I'm happy to address your concerns there if you are prepared to move to that version

**Comment by lilic** [comment]
Since we don't support the helm chart in this repo anymore, closing this issue. Feel free to open a new one if you think it's not valid, thanks!
